### ISSUE TITLE
Plugin fails to load w/ tmux 3.6a: invalid style: fg=border-strong

### ISSUE THREAD

**Issue by AdamIsrael** [fabioluciano/tmux-powerkit#126]
Hi,

Using the latest version of tmux, 3.6a, the plugin fails to load. I've managed to track it down to this error when `init.sh` is run:

```bash
bash -x init.sh
[...]
+ tmux set-option -g pane-active-border-style fg=border-strong
invalid style: fg=border-strong
```

The error causes tpm to fail: `'~/.tmux/plugins/tpm/tpm' returned 1`.

I'm not super familiar enough with tmux to debug this, but I'm happy to provide any other information.

**Comment by fabioluciano** [comment]
I think your problem is fixed now :)

**Comment by AdamIsrael** [comment]
Almost! But thank you for the quick response.

I found that I was still getting the error, but when I examined the logs I realized that it was checking for the tokyo-night `storm` theme, which doesn't have a script associated with it. When I changed to use night, it works fine.

This doesn't work:

```bash
set -g @powerkit_theme_variant 'storm'
```

But this does work:

```bash
set -g @powerkit_theme_variant 'night'
```

Here are the relevant logs from running `init.sh`:

```bash
++ theme=tokyo-night
+++ get_tmux_option @powerkit_theme_variant ''
+++ local option=@powerkit_theme_variant
+++ local default_value=
+++ local value
++++ tmux show-option -gqv @powerkit_theme_variant
+++ value=storm
+++ printf %s storm
++ theme_variant=storm
++ [[ -z storm ]]
++ [[ -z storm ]]
++ [[ -z tokyo-night ]]
++ [[ -z storm ]]
++ theme_file=/Users/adam/.tmux/plugins/tmux-powerkit/src/themes/tokyo-night/storm.sh
++ [[ -f /Users/adam/.tmux/plugins/tmux-powerkit/src/themes/tokyo-night/storm.sh ]]
++ printf %s surface
+ local border_style_inactive_pane=surface
+ tmux set-option -g pane-active-border-style fg=border-strong
invalid style: fg=border-strong
```

**Comment by fabioluciano** [comment]
I think you need to update the plugin again... In the past days i released a bunch of versions :D
